baseURL = "https://limityjsmemy.github.io/ljmtailwind"
title = "Blonde"
author = "wamo"
languageCode = "cs"
DefaultContentLanguage = "cs"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true
buildFuture = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]
featuredBackground = "jiretin.jpg"
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

[languages.cs]
contentDir = "content/czech"
languageCode = "cs-cz"
languageName = "Česky"
weight = 1

[languages.de]
contentDir = "content/deutsch"
languageCode = "de-de"
languageName = "Deutsch"
weight = 3

[languages.en]
contentDir = "content/english"
languageCode = "en-us"
languageName = "English"
weight = 2

[[menu.main_cs]]
identifier = "home"
name = "Úvodem"
url = "/"
weight = 1

[[menu.main_cs]]
identifier = "about"
name = "O nás"
url = "/about/"
weight = 2

[[menu.main_cs]]
identifier = "contact"
name = "Kontakt"
url = "/contact/"
weight = 3

[[menu.main_cs]]
identifier = "klimakemp2021"
name = "Klimakemp 2021"
url = "/contact/"
weight = 3

[[menu.main_cs]]
identifier = "newsletter"
name = "Odebírej náš newsletter"
url = "/#newsletter-box"
pre = "<svg xmlns = 'http://www.w3.org/2000/svg' width = '20' height = '20' viewBox = '0 0 24 24' fill = 'none' stroke = '#000000' stroke-width= '2' stroke-linecap = 'round' stroke-linejoin = 'round'><path d = 'M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z'></path><polyline points = '22,6 12,13 2,6'></polyline></svg>"
weight = 3

[[menu.main_en]]
identifier = "home"
name = "News"
url = "/"
weight = 1

[[menu.main_de]]
identifier = "home"
name = "Neues"
url = "/"
weight = 1

[[menu.header_cs]]
identifier = "primary"
name = "Přidej se k nám"
url = "/pridej-se/"
weight = 1

[[menu.header_cs]]
identifier = "secondary"
name = "Chci vědět víc"
url = "/o-nas/"
weight = 2

[[menu.social_links]]
identifier = "facebook"
url = "https://facebook.com"
[menu.social_links.params]
icon_path = "/icons/facebook.svg"

[[menu.social_links]]
identifier = "twitter"
url = "https://twitter.com"
[menu.social_links.params]
icon_path = "/icons/twitter.svg"

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
